name: Output Event Details on Issues
on: issues
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Event Details
              run: echo "what is this issue about? ${{ github.event.issue.title }}"